defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "resnet50ml"
pretrained_backbone: False
backbone:
  name: "resnet50ml"
data:
  dataset: radimagenet
  train_path: "/workspace/refined_radiology_ai_1L/train"
  val_path: "/workspace/refined_radiology_ai_1L/val"
  format: "dali"
  data_fraction: 0.1
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.1
  momentum: 0.9
  weight_decay: 1e-4
scheduler:
  name: "step"
  interval: "epoch"
  step_size: 30
  gamma: 0.1
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 90
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "auto"
precision: 16-mixed
